server:
  port: 8001

spring:
  application:
    name: auth-service
  cloud:
    zookeeper:
      connect-string: 8.140.250.103:2181
  data:
    redis:
      host: 8.140.250.103
      port: 6379
      password: 123456
  cache:
    type: redis
    redis:
      use-key-prefix: false
      cache-null-values: false
      time-to-live: 1000s